version: '3.9'

services:
  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: ${APPLICATION_ID}-nginx
    ports:
      - "${SERVER_PORT}:80"
      - "${SERVER_PORT_SSL}:443"
    volumes:
      - ~/projects/webifycms-stack/:/src
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
    networks:
      - webify-docker

  # php
  php-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ${APPLICATION_ID}-app
    entrypoint: sh ./docker/php/entrypoint.sh php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ~/projects/webifycms-stack/:/src
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/entrypoint.sh:/bin/php/entrypoint.sh
    networks:
      - webify-docker

  # mysql
  mysql-service:
    image: mysql:8
    container_name: ${APPLICATION_ID}-mysql
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    command: --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - webify-data:/var/lib/mysql
    networks:
      - webify-docker

  # node
  node-service:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: ${APPLICATION_ID}-node
    tty: true
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/app
    networks:
      - webify-docker

# docker network
networks:
  webify-docker:

# data persitence volumes
volumes:
  webify-data:
    driver: local
